sudo: required
services:
    - docker

before_install:
    - docker build -t pavloandriiesh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run pavloandriiesh/react-test npm test -- --coverage

after_success:
    - docker build -t pavloandriiesh/multi-client ./client
    - docker build -t pavloandriiesh/multi-server ./server
    - docker build -t pavloandriiesh/multi-worker ./worker
    - docker build -t pavloandriiesh/multi-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push pavloandriiesh/multi-client
    - docker push pavloandriiesh/multi-server
    - docker push pavloandriiesh/multi-worker
    - docker push pavloandriiesh/multi-nginx

deploy:
    provide: elasticbeanstalk
    region: "eu-west-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-712658749883"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY